### ISSUE TITLE
Failed to load the autocomplete-flow package

### ISSUE THREAD

**Issue by arv** [nmn/autocomplete-flow#4]
[Enter steps to reproduce below:]
1. Start Atom

**Atom Version**: 1.5.1
**System**: Mac OS X 10.11.2
**Thrown From**: [autocomplete-flow](https://github.com/nmn/autocomplete-flow) package, v1.3.0
### Stack Trace

Failed to load the autocomplete-flow package

```
At Cannot find module 'babel-runtime/helpers/typeof'

Error: Cannot find module 'babel-runtime/helpers/typeof'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/arv/.atom/packages/autocomplete-flow/build/index.js:3:16)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:722:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:395:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:684:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "sync-settings",
      "autosave"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "autocomplete-flow": {}
}
```
### Installed Packages

``` coffee
# User
atom-import-sort, v0.6.0
autocomplete-flow, v1.3.0
autocomplete-paths, v1.0.2
ctrl-last-tab, v0.3.0
file-types, v0.5.1
go-plus, v3.5.2
go-rename, v0.3.0
linter, v1.11.3
linter-eslint, v6.0.0
linter-flow, v4.1.0
travis-ci-status, v1.0.0

# Dev
No dev packages
```

**Comment by nmn** [comment]
This problem was fixed for me once I updated atom. Please try uninstalling and re-installing the package. I'll look into it on my end.

**Comment by arv** [comment]
Thanks. I just checked it on 1.6.0-beta1 and 1.5.1 and uninstall and reinstall. Same error.

Maybe you have some other package installed that installs `babel-runtime/helpers` for you?

**Comment by nmn** [comment]
Just updated the package. I moved 'babel-runtime' to dependencies from devDependencies.

Let me know if it still doesn't work.

**Comment by arv** [comment]
1.4 works like a charm. Thanks.
